### ISSUE TITLE
Incorrect action type labels in comment/directions

### ISSUE THREAD

**Issue by perryahern** [LambdaSchool/Redux-II-Mini#3]
Also in starWarsReducer, forgot this one before:

The comment in charsReducer labels the actions differently than what were specified actions/index.js and imported in the first line here.

import { FETCHING, FETCHED, ERRORS } from '../actions';

const initialState = {
  // define a few properties here.
  // Array chars, String fetching, String fetched, null error.
  chars: [],
  fetching: false,
  fetched: false,
  error: null,
};
export const charsReducer = (state = initialState, action) => {
  // Fill me in with the important reducers
  // action types should be FETCHING_CHARS, CHARS_RECEIVED, ERROR_FETCHING_CHARS
  // your switch statement should handle all of these cases.
  switch (action.type) {
    case FETCHING:
    return { ...state, fetching: true };
    case FETCHED:
    return {
        ...state,
        fetched: true,
        fetching: false,
        chars: action.payload.results
      }
    case ERRORS:
      return { ...state, fetching: false, error: action.payload };
    default:
      return state;
  }
};

**Comment by seanchen1991** [comment]
Fixed
